package ErroresYExcepciones;

public class tercerTryCatch
{

	public static void main(String[] args) 
	{
		int v1=4, v2=0;
		
		int resultado=operacion(v1,v2);
		
			System.out.println(resultado);
		
	}
	public static int operacion(int a, int b)
	{
		int resultado=0;
		try 
		{
			resultado= (a/b);
		}
		catch (ArithmeticException e) 
		{
			System.out.println(e.getMessage());	
		}
		
		return resultado;
	}
}
